name: forex-app
services:
  forex-proxy:
    environment:
      - APP_ENV=docker
    container_name: forex-proxy-provider
    restart: always
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080